version: "3.9"

services:
  localsecret-1:
    image: initc3/sgxonerated:62acbc925
    environment:
      LOG_LEVEL: "TRACE"
      SECRET_NODE_TYPE: BOOTSTRAP
      SNIP20_ATTACK_DIR: /root/snip20
    volumes:
      - genesis:/genesis
      - snip20:/root/snip20

  localsecret-2:
    image: initc3/sgxonerated:62acbc925
    environment:
      CHAINID: "secretdev-1"
      LOG_LEVEL: "TRACE"
      SECRET_NODE_TYPE: NODE
      SNIP20_ATTACK_DIR: /root/snip20
      ENCLAVE_KEY: io-master-key.txt
    volumes:
      - genesis:/genesis
      - snip20:/root/snip20
    depends_on:
      localsecret-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:26657"]
      interval: 3s
      timeout: 1s
      retries: 120
      start_period: 5s

  block-watcher:
    image: teebox
    build:
      context: teebox
      dockerfile: Dockerfile
    depends_on:
      localsecret-2:
        condition: service_healthy
    volumes:
      - ./teebox:/usr/src/teebox
    command: sleep 1

volumes:
  genesis:
  snip20:
