version: "3.9"
services:
  localsecret-1:
    image: devlocalsecret:98c5ef9fe
    build:
      context: ..
      dockerfile: hacking/Dockerfile
      target: build-localsecret
      args:
        FEATURES: "debug-print"
        SGX_MODE: SW
        SECRET_NODE_TYPE: BOOTSTRAP
        CHAIN_ID: secretdev-1
        IAS_BUILD: sw_dummy
      secrets:
        - API_KEY
        - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    #ports:
    #  - "26657:26657"
    #  - "26656:26656"
    #  - "9090:9090"
    #  - "9091:9091"
    #  - "1317:1317"
    #  # faucet
    #  - "5000:5000"
    environment:
      LOG_LEVEL: "TRACE"
      SECRET_NODE_TYPE: BOOTSTRAP
      #SNIP20_ATTACK_DIR: ${SNIP20_ATTACK_DIR}
      SNIP20_ATTACK_DIR: /root/snip20
    # NOTE: mount source code that may be changed and rebuilt in a container
    volumes:
      - ./scripts/:/root/scripts
      - ./teebox:/usr/src/teebox
      - genesis:/genesis
      - snip20:/root/snip20

  localsecret-2:
    image: devlocalsecret:98c5ef9fe
    build:
      context: ..
      dockerfile: hacking/Dockerfile
      target: build-localsecret
      args:
        FEATURES: "debug-print"
        SGX_MODE: SW
        CHAIN_ID: secretdev-1
        IAS_BUILD: sw_dummy
      secrets:
        - API_KEY
        - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    #ports:
    #  - "36657:26657"
    #  - "36656:26656"
    #  - "9391:9091"
    #  - "9390:9090"
    #  - "3317:1317"
    #  # faucet
    #  - "5300:5000"
    environment:
      CHAINID: "secretdev-1"
      LOG_LEVEL: "TRACE"
      SECRET_NODE_TYPE: NODE
      #SNIP20_ATTACK_DIR: ${SNIP20_ATTACK_DIR}
      #ENCLAVE_KEY: ${ENCLAVE_KEY}
      SNIP20_ATTACK_DIR: /root/snip20
      ENCLAVE_KEY: io-master-key.txt
    # NOTE: mount source code that may be changed and rebuilt in a container
    volumes:
      - ./scripts:/root/scripts
      - ./teebox:/usr/src/teebox
      - genesis:/genesis
      - snip20:/root/snip20
secrets:
  API_KEY:
    file: ../.env.local
  SPID:
    file: ../.env.local
volumes:
  genesis:
  snip20:
