version: "3.9"
services:
  localsecret-1:
    #image: initc3/localsecret:dac7bc254
    image: devlocalsecret:01a2e7904
    build:
      context: ..
      dockerfile: hacking/Dockerfile
      target: build-localsecret
      args:
        FEATURES: "debug-print"
        SGX_MODE: SW
        SECRET_NODE_TYPE: BOOTSTRAP
        CHAIN_ID: secretdev-1
        IAS_BUILD: sw_dummy
      secrets:
        - API_KEY
        - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    #ports:
    #  - "26657:26657"
    #  - "26656:26656"
    #  - "9090:9090"
    #  - "9091:9091"
    #  - "1317:1317"
    #  # faucet
    #  - "5000:5000"
    environment:
      LOG_LEVEL: "TRACE"
      SECRET_NODE_TYPE: BOOTSTRAP
      #SNIP20_ATTACK_DIR: ${SNIP20_ATTACK_DIR}
      SNIP20_ATTACK_DIR: /root/snip20
    # NOTE: mount source code that may be changed and rebuilt in a container
    volumes:
      #- ../go-cosmwasm/src:/go/src/github.com/enigmampc/SecretNetwork/go-cosmwasm/src
      - ./scripts/:/root/scripts
      #- ./backup_snip20:/root/backup_snip20
      #- ./backup_snip20:${SNIP20_ATTACK_DIR}
      - ./backup_snip20:/root/snip20
      - genesis:/genesis

  localsecret-2:
    #image: initc3/localsecret:dac7bc254
    image: devlocalsecret:01a2e7904
    build:
      context: ..
      dockerfile: hacking/Dockerfile
      target: build-localsecret
      args:
        FEATURES: "debug-print"
        SGX_MODE: SW
        CHAIN_ID: secretdev-1
        IAS_BUILD: sw_dummy
      secrets:
        - API_KEY
        - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    #ports:
    #  - "36657:26657"
    #  - "36656:26656"
    #  - "9391:9091"
    #  - "9390:9090"
    #  - "3317:1317"
    #  # faucet
    #  - "5300:5000"
    environment:
      CHAINID: "secretdev-1"
      LOG_LEVEL: "TRACE"
      SECRET_NODE_TYPE: NODE
      #SNIP20_ATTACK_DIR: ${SNIP20_ATTACK_DIR}
      #ENCLAVE_KEY: ${ENCLAVE_KEY}
      SNIP20_ATTACK_DIR: /root/snip20
      ENCLAVE_KEY: io-master-key.txt
    # NOTE: mount source code that may be changed and rebuilt in a container
    volumes:
    #  - ../go-cosmwasm/src:/go/src/github.com/enigmampc/SecretNetwork/go-cosmwasm/src
    #  - ../x:/go/src/github.com/enigmampc/SecretNetwork/x
    #  - ../app:/go/src/github.com/enigmampc/SecretNetwork/app
    #  - ./debug_scripts/:/root/debug_scripts
      - ./scripts:/root/scripts
        #- ./scripts/run_mev_demo_local.sh:/root/scripts/run_mev_demo_local.sh
        #- ./scripts/mev_utils.sh:/root/scripts/mev_utils.sh
        #- ./scripts/demo_utils.sh:/root/scripts/demo_utils.sh
        #- ./scripts/log_utils.sh:/root/scripts/log_utils.sh
    #  #- ./backup_snip20:/root/backup_snip20
    #  #- ./backup_snip20:${SNIP20_ATTACK_DIR}
      - ./backup_snip20:/root/snip20
      - genesis:/genesis
secrets:
  API_KEY:
    file: ../.env.local
  SPID:
    file: ../.env.local
volumes:
  genesis:
