version: "3.9"
services:
  localsecret-1:
    image: devlocalsecret
    build:
      context: ..
      dockerfile: hacking/dev.Dockerfile
      args:
        #BUILD_VERSION: ${VERSION}
        FEATURES: "${FEATURES},debug-print"
        FEATURES_U: ${FEATURES_U}
        SGX_MODE: SW
        SECRET_NODE_TYPE: BOOTSTRAP
        CHAIN_ID: secretdev-1
      secrets:
        - API_KEY
        - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "26657:26657"
      - "26656:26656"
      - "9090:9090"
      - "9091:9091"
      - "1317:1317"
      # faucet
      - "5000:5000"
    environment:
      LOG_LEVEL: "INFO"
      SECRET_NODE_TYPE: BOOTSTRAP
    # NOTE: mount source code that may be changed and rebuilt in a container
    volumes:
      - ../go-cosmwasm/src:/go/src/github.com/enigmampc/SecretNetwork/go-cosmwasm/src
      - ./secretd-1:/root/.secretd/

  localsecret-2:
    image: devlocalsecret
    build:
      context: ..
      dockerfile: hacking/dev.Dockerfile
      args:
        #BUILD_VERSION: ${VERSION}
        FEATURES: "${FEATURES},debug-print"
        FEATURES_U: ${FEATURES_U}
        SGX_MODE: SW
        CHAIN_ID: secretdev-1
      secrets:
        - API_KEY
        - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "36657:26657"
      - "36656:26656"
      - "9391:9091"
      - "9390:9090"
      - "3317:1317"
      # faucet
      - "5300:5000"
    environment:
      CHAINID: "secretdev-1"
      LOG_LEVEL: "INFO"
      SECRET_NODE_TYPE: NODE
      DUMMY_STORE: "true"
    # NOTE: mount source code that may be changed and rebuilt in a container
    volumes:
      - ../go-cosmwasm/src:/go/src/github.com/enigmampc/SecretNetwork/go-cosmwasm/src
      - ../go-cosmwasm/api:/go/src/github.com/enigmampc/SecretNetwork/go-cosmwasm/api
      - ../app:/go/src/github.com/enigmampc/SecretNetwork/app
      - ../proto:/go/src/github.com/enigmampc/SecretNetwork/proto
      - ../x:/go/src/github.com/enigmampc/SecretNetwork/x
      - ./scripts/:/root/scripts
      - ./secretd-2:/root/.secretd/
      - ./genesis:/tmp/genesis
      - ./contract-simple:/root/contract-simple
secrets:
  API_KEY:
    file: ../.env.local
  SPID:
    file: ../.env.local
