version: "3.9"
services:
  localsecret-1:
    image: devlocalsecret
    build:
      context: ..
      dockerfile: hacking/Dockerfile
      target: build-localsecret
      args:
        FEATURES: "${FEATURES},debug-print"
        FEATURES_U: ${FEATURES_U}
        SGX_MODE: SW
        SECRET_NODE_TYPE: BOOTSTRAP
        CHAIN_ID: secretdev-1
      secrets:
        - API_KEY
        - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "26657:26657"
      - "26656:26656"
      - "9090:9090"
      - "9091:9091"
      - "1317:1317"
      # faucet
      - "5000:5000"
    environment:
      LOG_LEVEL: "INFO"
      SECRET_NODE_TYPE: BOOTSTRAP
    # NOTE: mount source code that may be changed and rebuilt in a container
    volumes:
      - ../go-cosmwasm/src:/go/src/github.com/enigmampc/SecretNetwork/go-cosmwasm/src
      - ./scripts/:/root/scripts
      - ./backup_snip20:/root/backup_snip20
      - genesis:/genesis

  localsecret-2:
    image: devlocalsecret
    build:
      context: ..
      dockerfile: hacking/Dockerfile
      target: build-localsecret
      args:
        FEATURES: "${FEATURES},debug-print"
        FEATURES_U: ${FEATURES_U}
        SGX_MODE: SW
        CHAIN_ID: secretdev-1
      secrets:
        - API_KEY
        - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "36657:26657"
      - "36656:26656"
      - "9391:9091"
      - "9390:9090"
      - "3317:1317"
      # faucet
      - "5300:5000"
    environment:
      CHAINID: "secretdev-1"
      LOG_LEVEL: "INFO"
      SECRET_NODE_TYPE: NODE
    # NOTE: mount source code that may be changed and rebuilt in a container
    volumes:
      - ../go-cosmwasm/src:/go/src/github.com/enigmampc/SecretNetwork/go-cosmwasm/src
      - ../x:/go/src/github.com/enigmampc/SecretNetwork/x
      - ../app:/go/src/github.com/enigmampc/SecretNetwork/app
      - ./debug_scripts/:/root/debug_scripts
      - genesis:/genesis
      - ./scripts:/root/scripts
      - ./secretSCRT:/root/secretSCRT
      - ./backup_snip20:/root/backup_snip20
      - genesis:/genesis
secrets:
  API_KEY:
    file: ../.env.local
  SPID:
    file: ../.env.local
volumes:
  genesis:
