version: "3.9"

services:
  localsecret-1:
    image: initc3/localsecret:01a2e7904
    environment:
      LOG_LEVEL: "TRACE"
      SECRET_NODE_TYPE: BOOTSTRAP
      SNIP20_ATTACK_DIR: /root/snip20
    volumes:
      - genesis:/genesis

  localsecret-2:
    image: initc3/localsecret:01a2e7904
    environment:
      CHAINID: "secretdev-1"
      LOG_LEVEL: "TRACE"
      SECRET_NODE_TYPE: NODE
      SNIP20_ATTACK_DIR: /root/snip20
      ENCLAVE_KEY: io-master-key.txt
    volumes:
      - genesis:/genesis

volumes:
  genesis:
