version: "3.9"
services:
  localsecret-1:
    image: devlocalsecret-1
    build:
      context: ..
      dockerfile: hacking/Dockerfile
      target: build-localsecret
      args:
        #BUILD_VERSION: ${VERSION}
        FEATURES: "${FEATURES},debug-print"
        FEATURES_U: ${FEATURES_U}
        SGX_MODE: SW
        SECRET_NODE_TYPE: BOOTSTRAP
        CHAIN_ID: secretdev-1
      secrets:
        - API_KEY
        - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "26658:26657"
      - "26659:26656"
      - "9092:9090"
      - "9093:9091"
      - "1318:1317"
      # faucet
      - "5001:5000"
    environment:
      LOG_LEVEL: "INFO"
      SECRET_NODE_TYPE: BOOTSTRAP
    # NOTE: mount source code that may be changed and rebuilt in a container
    volumes:
      # - ../go-cosmwasm/src:/go/src/github.com/enigmampc/SecretNetwork/go-cosmwasm/src
      - ./secretd-1:/root/.secretd/
      - ./scripts/:/root/scripts

  localsecret-2:
    image: devlocalsecret-1
    build:
      context: ..
      dockerfile: hacking/Dockerfile
      target: build-localsecret
      args:
        #BUILD_VERSION: ${VERSION}
        FEATURES: "${FEATURES},debug-print"
        FEATURES_U: ${FEATURES_U}
        SGX_MODE: SW
        CHAIN_ID: secretdev-1
      secrets:
        - API_KEY
        - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "36658:26657"
      - "36659:26656"
      - "9392:9091"
      - "9393:9090"
      - "3318:1317"
      # faucet
      - "5400:5000"
    environment:
      CHAINID: "secretdev-1"
      LOG_LEVEL: "INFO"
      SECRET_NODE_TYPE: NODE
      DUMMY_STORE: "true"
    # NOTE: mount source code that may be changed and rebuilt in a container
    volumes:
      # - ../go-cosmwasm/src:/go/src/github.com/enigmampc/SecretNetwork/go-cosmwasm/src
      # - ../go-cosmwasm/api:/go/src/github.com/enigmampc/SecretNetwork/go-cosmwasm/api
      # - ../proto:/go/src/github.com/enigmampc/SecretNetwork/proto
      - ../x:/go/src/github.com/enigmampc/SecretNetwork/x
      - ../app:/go/src/github.com/enigmampc/SecretNetwork/app
      - ./scripts/:/root/scripts
      - ./secretd-2:/root/.secretd/
      - ./genesis:/tmp/genesis
      - ./contract-simple:/root/contract-simple
      - ./contract-sienna-swap:/root/contract-sienna-swap
      - ../cosmos-sdk:/go/src/github.com/enigmampc/SecretNetwork/cosmos-sdk
secrets:
  API_KEY:
    file: ../.env.local
  SPID:
    file: ../.env.local
