name: publish-scrt-devnet-image

on:
  push:
    branches: [ demo ]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish-devnet-image:
    env:
      IMAGE_NAME: initc3/scrt-devnet
    strategy:
      matrix:
        node_type: ["BOOTSTRAP", "NODE"]

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build & publish docker image for scrt devnet
        uses: docker/build-push-action@v4
        with:
          context: .
          file: hacking/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: |
            FEATURES: "debug-print"
            SGX_MODE: SW
            SECRET_NODE_TYPE: ${{ matrix.node_type }}
            CHAIN_ID: secretdev-1
            IAS_BUILD: sw_dummy
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.node_type }},
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.node_type }}-${{ steps.vars.outputs.short_sha }},
          cache-from: type=gha
          cache-to: type=gha,mode=max
